/// <reference types="react" />
/// <reference types="react-dom" />
/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />

// Do not edit this file manually; it ensures TypeScript recognizes Next.js and React modules

declare module 'next/navigation';
declare module 'next/link';
declare module 'next/image';
